# Logistic Regression

In [1]:
!pip install tensorflow

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import tensorflow as tf

In [11]:
x_data = [[1, 2], [2, 3], [3, 1], [4,3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

# X에서 들어오는 갯수, 나가는 값의 갯수 
W = tf.Variable(tf.random_normal([2, 1]), name='weight')

# 나가는 값의 갯수
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W) + b))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1-hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis > 0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    #Initialize Tensorflow variables
    sess.run(tf.global_variables_initializer())
    
    print("\nstep\tcost\n")
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, "\t", cost_val)
            
    # Accuracy Report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: \n", h, "\nCorrect (Y): \n", c, "\nAccuracy: \n", a)


step	cost

0 	 1.90728
200 	 0.918116
400 	 0.650565
600 	 0.541122
800 	 0.489425
1000 	 0.458726
1200 	 0.436769
1400 	 0.419015
1600 	 0.403581
1800 	 0.389609
2000 	 0.376675
2200 	 0.364557
2400 	 0.353125
2600 	 0.3423
2800 	 0.332027
3000 	 0.322264
3200 	 0.312977
3400 	 0.304138
3600 	 0.295719
3800 	 0.287697
4000 	 0.280048
4200 	 0.272752
4400 	 0.265788
4600 	 0.259139
4800 	 0.252785
5000 	 0.24671
5200 	 0.240899
5400 	 0.235337
5600 	 0.23001
5800 	 0.224904
6000 	 0.220009
6200 	 0.215311
6400 	 0.210801
6600 	 0.206468
6800 	 0.202303
7000 	 0.198298
7200 	 0.194443
7400 	 0.190731
7600 	 0.187154
7800 	 0.183707
8000 	 0.180381
8200 	 0.177172
8400 	 0.174074
8600 	 0.171081
8800 	 0.168188
9000 	 0.16539
9200 	 0.162684
9400 	 0.160064
9600 	 0.157527
9800 	 0.155069
10000 	 0.152687

Hypothesis: 
 [[ 0.03209435]
 [ 0.16064303]
 [ 0.31128016]
 [ 0.77846771]
 [ 0.93772316]
 [ 0.97954923]] 
Correct (Y): 
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]] 
Accuracy: 
 1.0


# Classifying diabetes

In [12]:
import numpy as np

In [26]:
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholder for a tensor that will be alaways fed
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis > 0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    #Initialize Tensorflow variables
    sess.run(tf.global_variables_initializer())
    
    feed = {X: x_data, Y: y_data}
    print("\nstep\tcost\n")
    for step in range(10001):
        sess.run(train, feed_dict=feed)
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict=feed))
            
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print("\nHypothesis: \n", h, "\nCorrect (Y):\n", c, "\nAccuracy\n", a)


step	cost

0 1.12819
200 0.80405
400 0.727459
600 0.692528
800 0.666709
1000 0.644966
1200 0.626216
1400 0.609984
1600 0.595913
1800 0.583694
2000 0.573058
2200 0.563774
2400 0.555641
2600 0.548491
2800 0.542181
3000 0.536591
3200 0.531618
3400 0.527178
3600 0.523199
3800 0.51962
4000 0.516389
4200 0.513462
4400 0.510803
4600 0.508379
4800 0.506164
5000 0.504133
5200 0.502267
5400 0.500548
5600 0.498961
5800 0.497493
6000 0.496131
6200 0.494866
6400 0.493689
6600 0.492591
6800 0.491567
7000 0.490608
7200 0.489711
7400 0.488869
7600 0.488079
7800 0.487336
8000 0.486637
8200 0.485979
8400 0.485358
8600 0.484771
8800 0.484217
9000 0.483693
9200 0.483197
9400 0.482727
9600 0.482282
9800 0.481859
10000 0.481458

Hypothesis: 
 [[ 0.40779987]
 [ 0.92673647]
 [ 0.27094379]
 [ 0.93928903]
 [ 0.11663734]
 [ 0.77935719]
 [ 0.93571329]
 [ 0.60082257]
 [ 0.29968244]
 [ 0.51635981]
 [ 0.69076109]
 [ 0.17981702]
 [ 0.2240766 ]
 [ 0.3393195 ]
 [ 0.73028576]
 [ 0.40060249]
 [ 0.73582333]
 [ 0.82963204